<?php

namespace Database\Seeders;

use App\Models\ContactInquiry;
use App\Models\NewsletterSubscriber;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ContactAndNewsletterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->seedContactInquiries();
        $this->seedNewsletterSubscribers();
    }

    protected function seedContactInquiries(): void
    {
        $inquiries = [
            [
                'name' => 'Nguyễn Minh Tuấn',
                'title' => 'Giám đốc Thiết kế Chiếu sáng',
                'company' => 'Lux Studio Architects & Lighting',
                'email' => 'tuan.nguyen@luxstudio.vn',
                'phone' => '0912 345 678',
                'enquiry_type' => 'Sales Enquiry',
                'status' => ContactInquiry::STATUS_NEW,
                'message' => 'Chào LuxLight, bên mình đang thực hiện gói thiết kế MEP & chiếu sáng cảnh quan cho khu nghỉ dưỡng 5 sao Regent Phú Quốc giai đoạn 2. Cần tư vấn giải pháp đèn facade và âm sàn ngoài trời của hãng Aldabra và Acolyte. Vui lòng gửi catalogue và bảng giá dự án giúp mình.',
                'admin_notes' => null,
                'ip_address' => '118.69.182.45',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-09-09 09:30:00'),
                'replied_at' => null,
            ],
            [
                'name' => 'Trần Thị Thu Hà',
                'title' => 'Trưởng phòng Mua hàng & Vật tư',
                'company' => 'Vingroup Hospitality Project Management',
                'email' => 'ha.ttt@vingroup-hospitality.com.vn',
                'phone' => '0903 888 999',
                'enquiry_type' => 'Sales Enquiry',
                'status' => ContactInquiry::STATUS_PROCESSING,
                'message' => 'Chúng tôi cần chào thầu thiết bị đèn trang trí kiến trúc và linear lighting cho khối podium trung tâm thương mại Vincom Mega Mall. Dự kiến khối lượng khoảng 2.500 mét đèn thanh nhôm định hình cao cấp nhập khẩu.',
                'admin_notes' => 'Đã liên hệ sơ bộ qua điện thoại lúc 14h. Khách yêu cầu gửi mẫu thanh profile nhôm và dải LED Acolyte trước ngày 15/09.',
                'ip_address' => '14.161.24.110',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-09-08 14:15:00'),
                'replied_at' => null,
            ],
            [
                'name' => 'Marcus Vance',
                'title' => 'Senior Architectural Lighting Designer',
                'company' => 'B+H Architects Singapore',
                'email' => 'marcus.vance@bharchitects.com',
                'phone' => '+65 6738 8900',
                'enquiry_type' => 'Technical Enquiry',
                'status' => ContactInquiry::STATUS_REPLIED,
                'message' => 'We are specifying architectural luminaires for an ultra-luxury penthouse project in District 1, HCMC. Could your technical engineering team provide Dialux IES photometric files and dimming protocol compatibility (DALI-2 / 0-10V) for Aldabra downlights?',
                'admin_notes' => 'Đã gửi bộ file IES và datasheet kỹ thuật quang học qua email. Kỹ sư ánh sáng LuxLight đã hẹn họp online hỗ trợ mô phỏng Dialux.',
                'ip_address' => '202.166.195.8',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_6_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15',
                'created_at' => Carbon::parse('2026-09-06 16:20:00'),
                'replied_at' => Carbon::parse('2026-09-07 10:45:00'),
            ],
            [
                'name' => 'Lê Hoàng Nam',
                'title' => 'Kiến trúc sư trưởng',
                'company' => 'HOMA Architects Vietnam',
                'email' => 'nam.le@homa-architects.com',
                'phone' => '0989 123 456',
                'enquiry_type' => 'Sales Enquiry',
                'status' => ContactInquiry::STATUS_NEW,
                'message' => 'Cần tư vấn giải pháp chiếu sáng nghệ thuật thông tầng cho biệt thự đơn lập Chateau Phú Mỹ Hưng. Cần các mẫu đèn chùm nghệ thuật và hệ thống chiếu sáng thông minh tích hợp KNX/Lutron.',
                'admin_notes' => null,
                'ip_address' => '113.161.72.33',
                'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
                'created_at' => Carbon::parse('2026-09-09 11:00:00'),
                'replied_at' => null,
            ],
            [
                'name' => 'Phạm Quỳnh Anh',
                'title' => 'Phó Giám đốc Ban QLDA',
                'company' => 'Sun Hospitality Group',
                'email' => 'quynhanh.pham@sunhospitality.vn',
                'phone' => '0978 654 321',
                'enquiry_type' => 'Sales Enquiry',
                'status' => ContactInquiry::STATUS_PROCESSING,
                'message' => 'Xin chào, Sun Group đang triển khai khu tổ hợp biệt thự biển nghỉ dưỡng tại Đà Nẵng. Chúng tôi muốn đặt lịch xem mẫu thực tế các dòng đèn chống ăn mòn muối biển IP67/IP68 và đèn hắt cột kiến trúc ngoài trời.',
                'admin_notes' => 'Đã xếp lịch tiếp đoàn tư vấn Sun Group tại showroom LuxLight vào sáng thứ 6 tuần này.',
                'ip_address' => '115.79.136.21',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-09-07 08:30:00'),
                'replied_at' => null,
            ],
            [
                'name' => 'Hoàng Văn Đức',
                'title' => 'Kỹ sư trưởng MEP',
                'company' => 'Coteccons Construction JSC',
                'email' => 'duc.hv@coteccons.vn',
                'phone' => '0934 567 890',
                'enquiry_type' => 'Technical Enquiry',
                'status' => ContactInquiry::STATUS_REPLIED,
                'message' => 'Yêu cầu cung cấp hồ sơ năng lực, chứng chỉ CO/CQ và phương án sơ đồ đấu nối tủ điều khiển DMX cho hệ thống chiếu sáng mặt đứng tòa nhà văn phòng hạng A.',
                'admin_notes' => 'Đã bàn giao bộ hồ sơ CO/CQ Châu Âu và sơ đồ nguyên lý điều khiển DMX512 cho ban chỉ huy công trường.',
                'ip_address' => '171.244.13.82',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0',
                'created_at' => Carbon::parse('2026-09-04 10:10:00'),
                'replied_at' => Carbon::parse('2026-09-05 15:30:00'),
            ],
            [
                'name' => 'Vũ Bích Ngọc',
                'title' => 'Giám đốc Thiết kế Nội thất',
                'company' => 'AA Corporation',
                'email' => 'ngoc.vu@aacorporation.com',
                'phone' => '0918 765 432',
                'enquiry_type' => 'Feedback',
                'status' => ContactInquiry::STATUS_REPLIED,
                'message' => 'Đội ngũ LuxLight giao hàng và hỗ trợ căn chỉnh góc chiếu (aiming) tại công trình khách sạn boutique rất chuyên nghiệp. Ánh sáng ấm 2700K lên màu nội thất gỗ óc chó rất chuẩn xác và sang trọng.',
                'admin_notes' => 'Khách hàng rất hài lòng với chất lượng ánh sáng hoàn màu CRI>95. Đã gửi thư cảm ơn và catalogue các bộ sưu tập đèn chùm mới.',
                'ip_address' => '42.112.98.54',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-09-01 14:00:00'),
                'replied_at' => Carbon::parse('2026-09-02 11:00:00'),
            ],
            [
                'name' => 'David Chen',
                'title' => 'Senior Sourcing Manager',
                'company' => 'CapitaLand Development Vietnam',
                'email' => 'david.chen@capitaland.com',
                'phone' => '+84 28 3823 8888',
                'enquiry_type' => 'Sales Enquiry',
                'status' => ContactInquiry::STATUS_NEW,
                'message' => 'We would like to request product samples and project pricing for the upcoming high-end residential tower in Thu Thiem. Please assign a senior sales representative to contact us directly.',
                'admin_notes' => null,
                'ip_address' => '27.72.105.19',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-09-09 13:45:00'),
                'replied_at' => null,
            ],
            [
                'name' => 'Đỗ Thanh Tùng',
                'title' => 'Chuyên viên Tư vấn Chiếu sáng',
                'company' => 'Archetype Group',
                'email' => 'tung.do@archetype-group.com',
                'phone' => '0908 112 233',
                'enquiry_type' => 'Technical Enquiry',
                'status' => ContactInquiry::STATUS_PROCESSING,
                'message' => 'Chúng tôi cần tài liệu thông số kỹ thuật về giải pháp Human Centric Lighting (chiếu sáng lấy con người làm trung tâm) và dải điều chỉnh nhiệt độ màu CCT Tunable White 2200K - 6500K cho dự án y tế cao cấp.',
                'admin_notes' => 'Đang chờ hãng gửi bản cập nhật test report quang học photobiological safety IEC 62471.',
                'ip_address' => '118.70.190.12',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-09-08 09:00:00'),
                'replied_at' => null,
            ],
            [
                'name' => 'Bùi Mai Linh',
                'title' => 'Quản lý Dự án Bất động sản',
                'company' => 'BIM Land (BIM Group)',
                'email' => 'linh.bm@bimvietnam.com',
                'phone' => '0945 999 111',
                'enquiry_type' => 'Sales Enquiry',
                'status' => ContactInquiry::STATUS_REPLIED,
                'message' => 'BIM Land cần bảng chào giá chi tiết cho gói thiết bị chiếu sáng cảnh quan công viên nước và lối đi dạo bờ biển tại Hạ Long Marina. Yêu cầu sản phẩm chịu môi trường biển ăn mòn cao.',
                'admin_notes' => 'Đã gửi báo giá giai đoạn 1 cho ban QLDA. Khách đang trình phê duyệt ngân sách.',
                'ip_address' => '14.232.180.65',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-08-28 15:20:00'),
                'replied_at' => Carbon::parse('2026-08-29 17:00:00'),
            ],
            [
                'name' => 'Lý Gia Hưng',
                'title' => 'Kiến trúc sư độc lập',
                'company' => 'Hưng Architecture Studio',
                'email' => 'giahung.arch@gmail.com',
                'phone' => '0966 333 444',
                'enquiry_type' => 'Other',
                'status' => ContactInquiry::STATUS_ARCHIVED,
                'message' => 'Em đang thiết kế biệt thự gia đình ở Thảo Điền, muốn ghé qua showroom để xem các mẫu đèn rọi gắn ray nam châm (magnetic track light) của bên mình vào cuối tuần có mở cửa không ạ?',
                'admin_notes' => 'Đã liên hệ tư vấn và chuyển thông tin cho đại lý bán lẻ đối tác khu vực TP.HCM chăm sóc.',
                'ip_address' => '113.160.88.29',
                'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
                'created_at' => Carbon::parse('2026-08-15 11:30:00'),
                'replied_at' => Carbon::parse('2026-08-15 14:00:00'),
            ],
            [
                'name' => 'Ngô Thu Trang',
                'title' => 'Đại diện Văn phòng Thiết kế',
                'company' => 'MIA Design Studio',
                'email' => 'trang.ngo@miadesignstudio.com',
                'phone' => '0909 555 777',
                'enquiry_type' => 'Sales Enquiry',
                'status' => ContactInquiry::STATUS_ARCHIVED,
                'message' => 'Chào LuxLight, MIA muốn kết hợp cùng LuxLight đưa các mẫu đèn âm tường tối giản vào cuốn lookbook kiến trúc mới cho chuỗi villa nghỉ dưỡng ven sông.',
                'admin_notes' => 'Dự án đã hoàn thành bàn giao nghiệm thu.',
                'ip_address' => '222.252.30.14',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
                'created_at' => Carbon::parse('2026-08-10 16:40:00'),
                'replied_at' => Carbon::parse('2026-08-11 09:30:00'),
            ],
        ];

        foreach ($inquiries as $item) {
            ContactInquiry::query()->updateOrCreate(
                ['email' => $item['email']],
                $item
            );
        }
    }

    protected function seedNewsletterSubscribers(): void
    {
        $subscribers = [
            [
                'first_name' => 'Tuấn',
                'last_name' => 'Nguyễn Minh',
                'email' => 'tuan.nguyen@luxstudio.vn',
                'company' => 'Lux Studio Architects',
                'referral' => 'Search Engine',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-09 09:32:00'),
                'unsubscribed_at' => null,
                'ip_address' => '118.69.182.45',
            ],
            [
                'first_name' => 'Hà',
                'last_name' => 'Trần Thị Thu',
                'email' => 'ha.ttt@vingroup-hospitality.com.vn',
                'company' => 'Vingroup Hospitality',
                'referral' => 'Referral',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-08 14:20:00'),
                'unsubscribed_at' => null,
                'ip_address' => '14.161.24.110',
            ],
            [
                'first_name' => 'Marcus',
                'last_name' => 'Vance',
                'email' => 'marcus.vance@bharchitects.com',
                'company' => 'B+H Architects Singapore',
                'referral' => 'Event / Exhibition',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-06 16:25:00'),
                'unsubscribed_at' => null,
                'ip_address' => '202.166.195.8',
            ],
            [
                'first_name' => 'Nam',
                'last_name' => 'Lê Hoàng',
                'email' => 'nam.le@homa-architects.com',
                'company' => 'HOMA Architects',
                'referral' => 'Social Media',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-09 11:05:00'),
                'unsubscribed_at' => null,
                'ip_address' => '113.161.72.33',
            ],
            [
                'first_name' => 'Quỳnh Anh',
                'last_name' => 'Phạm',
                'email' => 'quynhanh.pham@sunhospitality.vn',
                'company' => 'Sun Hospitality Group',
                'referral' => 'Referral',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-07 08:35:00'),
                'unsubscribed_at' => null,
                'ip_address' => '115.79.136.21',
            ],
            [
                'first_name' => 'Đức',
                'last_name' => 'Hoàng Văn',
                'email' => 'duc.hv@coteccons.vn',
                'company' => 'Coteccons Construction',
                'referral' => 'Search Engine',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-04 10:15:00'),
                'unsubscribed_at' => null,
                'ip_address' => '171.244.13.82',
            ],
            [
                'first_name' => 'Ngọc',
                'last_name' => 'Vũ Bích',
                'email' => 'ngoc.vu@aacorporation.com',
                'company' => 'AA Corporation',
                'referral' => 'Event / Exhibition',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-01 14:05:00'),
                'unsubscribed_at' => null,
                'ip_address' => '42.112.98.54',
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Chen',
                'email' => 'david.chen@capitaland.com',
                'company' => 'CapitaLand Vietnam',
                'referral' => 'Search Engine',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-09 13:50:00'),
                'unsubscribed_at' => null,
                'ip_address' => '27.72.105.19',
            ],
            [
                'first_name' => 'Tùng',
                'last_name' => 'Đỗ Thanh',
                'email' => 'tung.do@archetype-group.com',
                'company' => 'Archetype Group',
                'referral' => 'Referral',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-08 09:05:00'),
                'unsubscribed_at' => null,
                'ip_address' => '118.70.190.12',
            ],
            [
                'first_name' => 'Linh',
                'last_name' => 'Bùi Mai',
                'email' => 'linh.bm@bimvietnam.com',
                'company' => 'BIM Land',
                'referral' => 'Event / Exhibition',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-08-28 15:25:00'),
                'unsubscribed_at' => null,
                'ip_address' => '14.232.180.65',
            ],
            [
                'first_name' => 'Trang',
                'last_name' => 'Ngô Thu',
                'email' => 'trang.ngo@miadesignstudio.com',
                'company' => 'MIA Design Studio',
                'referral' => 'Social Media',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-08-10 16:45:00'),
                'unsubscribed_at' => null,
                'ip_address' => '222.252.30.14',
            ],
            [
                'first_name' => 'Hương',
                'last_name' => 'Lê Diệu',
                'email' => 'dieu.huong@intercon-hanoi.vn',
                'company' => 'InterContinental Hanoi Westlake',
                'referral' => 'Event / Exhibition',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-05 11:20:00'),
                'unsubscribed_at' => null,
                'ip_address' => '118.70.144.9',
            ],
            [
                'first_name' => 'Khánh',
                'last_name' => 'Võ Quốc',
                'email' => 'khanh.vo@novaland.com.vn',
                'company' => 'Novaland Group',
                'referral' => 'Search Engine',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-03 16:40:00'),
                'unsubscribed_at' => null,
                'ip_address' => '14.169.32.77',
            ],
            [
                'first_name' => 'Minh',
                'last_name' => 'Đặng Nhật',
                'email' => 'nhatminh.arch@gmail.com',
                'company' => 'DNM Atelier',
                'referral' => 'Social Media',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-09-02 08:15:00'),
                'unsubscribed_at' => null,
                'ip_address' => '113.161.45.18',
            ],
            [
                'first_name' => 'Sophie',
                'last_name' => 'Laurent',
                'email' => 'sophie.laurent@dwp.com',
                'company' => 'Design Worldwide Partnership (dwp)',
                'referral' => 'Referral',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-08-25 10:30:00'),
                'unsubscribed_at' => null,
                'ip_address' => '171.250.21.114',
            ],
            [
                'first_name' => 'Phương',
                'last_name' => 'Nguyễn Mai',
                'email' => 'phuong.nguyen@k-decor.vn',
                'company' => 'K-Decor Construction',
                'referral' => 'Search Engine',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-08-20 14:50:00'),
                'unsubscribed_at' => null,
                'ip_address' => '115.74.88.92',
            ],
            [
                'first_name' => 'Trọng',
                'last_name' => 'Bùi Đức',
                'email' => 'ductrong@delta-corp.vn',
                'company' => 'DELTA Group Vietnam',
                'referral' => 'Event / Exhibition',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-08-14 09:10:00'),
                'unsubscribed_at' => null,
                'ip_address' => '14.238.102.51',
            ],
            [
                'first_name' => 'Alexander',
                'last_name' => 'Schmidt',
                'email' => 'a.schmidt@gmp.de',
                'company' => 'gmp Architekten',
                'referral' => 'Other',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-08-05 15:45:00'),
                'unsubscribed_at' => null,
                'ip_address' => '195.14.220.10',
            ],
            [
                'first_name' => 'Thảo',
                'last_name' => 'Dương Phương',
                'email' => 'thaodp@masterisehomes.com',
                'company' => 'Masterise Homes',
                'referral' => 'Search Engine',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-07-28 17:00:00'),
                'unsubscribed_at' => null,
                'ip_address' => '118.69.200.7',
            ],
            [
                'first_name' => 'Huy',
                'last_name' => 'Trịnh Quốc',
                'email' => 'quochuy.lighting@gmail.com',
                'company' => 'Freelance Lighting Designer',
                'referral' => 'Social Media',
                'is_active' => true,
                'subscribed_at' => Carbon::parse('2026-07-15 13:20:00'),
                'unsubscribed_at' => null,
                'ip_address' => '113.162.19.64',
            ],
            // Unsubscribed cases for realistic KPI demonstration
            [
                'first_name' => 'Thắng',
                'last_name' => 'Vũ Đình',
                'email' => 'thang.vd@vietinbank.vn',
                'company' => 'VietinBank Headquarter',
                'referral' => 'Other',
                'is_active' => false,
                'subscribed_at' => Carbon::parse('2026-06-10 10:00:00'),
                'unsubscribed_at' => Carbon::parse('2026-08-01 11:30:00'),
                'ip_address' => '123.30.180.12',
            ],
            [
                'first_name' => 'Kim',
                'last_name' => 'Young-Ho',
                'email' => 'youngho.kim@lotte.vn',
                'company' => 'Lotte Land Vietnam',
                'referral' => 'Event / Exhibition',
                'is_active' => false,
                'subscribed_at' => Carbon::parse('2026-06-20 14:10:00'),
                'unsubscribed_at' => Carbon::parse('2026-08-18 16:45:00'),
                'ip_address' => '210.245.10.88',
            ],
        ];

        foreach ($subscribers as $item) {
            NewsletterSubscriber::query()->updateOrCreate(
                ['email' => $item['email']],
                array_merge($item, [
                    'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
                ])
            );
        }
    }
}
